# -*- coding: utf-8 -*-
"""0316用地

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PeI4RpIMx0H9O1dYOOi9awjpFS3a3di7
"""

# ============================================================
# セル1: インストール & 認証
# ============================================================


from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default

creds, _ = default()
gc = gspread.authorize(creds)

# ★ 以下1行を編集してください ★
SPREADSHEET_ID = "1SI3I83QLjQ7UCUOHEyBL0gmwarnLAT_dR9QwDvSgSoA"  # スプレッドシートのID（URLの /d/〇〇〇/edit の〇〇〇部分）

SHEET_NAME         = "パトロール結果"  # 詳細データシート名
SUMMARY_SHEET_NAME = "サマリー"        # サマリーシート名

sh = gc.open_by_key(SPREADSHEET_ID)

def get_or_create_sheet(spreadsheet, name, rows=100, cols=10):
    try:
        ws = spreadsheet.worksheet(name)
        print(f"✅ 既存シートに接続: '{name}'")
    except gspread.exceptions.WorksheetNotFound:
        ws = spreadsheet.add_worksheet(title=name, rows=rows, cols=cols)
        print(f"✅ 新規シートを作成: '{name}'")
    return ws

ws         = get_or_create_sheet(sh, SHEET_NAME)
ws_summary = get_or_create_sheet(sh, SUMMARY_SHEET_NAME)

print(f"✅ スプレッドシート接続OK: {sh.title}")

# ============================================================
# セル2: 共通関数
# ============================================================
import requests
from bs4 import BeautifulSoup
import datetime
import re
import time
import chardet

TODAY = datetime.date.today()
TODAY_STR = TODAY.strftime("%Y/%m/%d")

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

# 対象エリアフィルター
TARGET_WARDS  = ["平野区", "東住吉区", "阿倍野区", "住吉区", "住之江区", "天王寺区", "生野区", "浪速区"]
TARGET_CITIES = ["松原市", "羽曳野市", "藤井寺市", "柏原市", "東大阪市", "八尾市", "富田林市", "堺市", "高石市"]
TARGET_AREAS  = TARGET_WARDS + TARGET_CITIES

# サマリーシートに表示する固定順序
SITES_ORDER = [
    "大阪府1（財産活用課）",
    "大阪府2（府営住宅用地）",
    "大阪市①（契約管財局）",
    "大阪市②（水道局）",
    "近畿財務局",
    "松原市",
    "堺市",
    "藤井寺市",
    "羽曳野市",
    "八尾市",
]


def fetch_page(url, timeout=15):
    """URLからHTMLを取得しBeautifulSoupオブジェクトを返す。失敗時は (None, エラーメッセージ) を返す。"""
    try:
        resp = requests.get(url, headers=HEADERS, timeout=timeout)
        resp.raise_for_status()
        detected = chardet.detect(resp.content)
        enc = (detected.get("encoding") or "utf-8").lower()
        if enc in ("shift_jis", "shift-jis", "sjis", "cp932"):
            resp.encoding = "cp932"
        elif enc in ("euc-jp", "euc_jp"):
            resp.encoding = "euc-jp"
        else:
            resp.encoding = enc
        return BeautifulSoup(resp.text, "html.parser"), None
    except requests.exceptions.Timeout:
        return None, "タイムアウト"
    except requests.exceptions.ConnectionError:
        return None, "接続エラー"
    except requests.exceptions.HTTPError as e:
        return None, f"HTTPエラー {e.response.status_code}"
    except Exception as e:
        return None, f"エラー: {e}"


def is_target_area(text):
    return any(area in text for area in TARGET_AREAS)


def make_row(jichitai, status, summary="", location="", period="", url="", pub_date=""):
    """
    スプレッドシート1行分のリストを返す。
    インデックス: 0=調査日, 1=自治体, 2=ステータス, 3=案件概要,
                 4=所在地, 5=申込期間, 6=URL, 7=公開日・更新日
    """
    return [TODAY_STR, jichitai, status, summary, location, period, url, pub_date]


def parse_date_jp(date_str):
    """日本語日付文字列をdatetime.dateに変換。失敗時はNone。"""
    m = re.search(r"令和(\d+)年(\d+)月(\d+)日", date_str)
    if m:
        return datetime.date(2018 + int(m.group(1)), int(m.group(2)), int(m.group(3)))
    m = re.search(r"(\d{4})年(\d+)月(\d+)日", date_str)
    if m:
        return datetime.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    m = re.search(r"(\d{4})[/\-](\d{1,2})[/\-](\d{1,2})", date_str)
    if m:
        return datetime.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    return None


def extract_period_end(period_text):
    """申込期間テキストから終了日を抽出。失敗時はNone。"""
    for pattern in [
        r"[〜～]\s*(令和\d+年\d+月\d+日|\d{4}年\d+月\d+日|\d{4}/\d+/\d+)",
        r"(令和\d+年\d+月\d+日|\d{4}年\d+月\d+日|\d{4}/\d+/\d+)\s*(?:まで|終了)",
    ]:
        m = re.search(pattern, period_text)
        if m:
            return parse_date_jp(m.group(1))
    return None


def extract_page_date(soup):
    """ページから公開日・更新日を抽出。失敗時は空文字。"""
    if soup is None:
        return ""
    text = soup.get_text(separator="\n")
    for pattern in [
        r"更新日[：:]\s*(令和\d+年\d+月\d+日|\d{4}年\d+月\d+日)",
        r"公開日[：:]\s*(令和\d+年\d+月\d+日|\d{4}年\d+月\d+日)",
        r"掲載日[：:]\s*(令和\d+年\d+月\d+日|\d{4}年\d+月\d+日)",
        r"情報公開日[：:]\s*(令和\d+年\d+月\d+日|\d{4}年\d+月\d+日)",
    ]:
        m = re.search(pattern, text)
        if m:
            return m.group(1)
    return ""


print(f"✅ 共通関数定義完了")
print(f"調査日: {TODAY_STR}")

# ============================================================
# セル3: 各サイトパーサー関数
# ============================================================

# ----------------------------------------
# 1. 大阪府1（財産活用課）
# ----------------------------------------
def parse_osaka_pref1():
    url = "https://www.pref.osaka.lg.jp/o050050/kanzai/baikyakutou/index.html"
    jichitai = "大阪府1（財産活用課）"

    soup, err = fetch_page(url)
    if err:
        print(f"[{jichitai}] ⚠️ {err}")
        return [make_row(jichitai, "⚠️ 確認不可", f"アクセスエラー: {err}", url=url)]

    pub_date = extract_page_date(soup)

    # 「新着情報」見出しを探す
    shinchaku = None
    for tag in soup.find_all(["h2", "h3", "h4", "h5", "p", "div", "span"]):
        if "新着情報" in tag.get_text(strip=True):
            shinchaku = tag
            break

    if shinchaku is None:
        print(f"[{jichitai}] ⚠️ 新着情報セクションが見つかりません")
        return [make_row(jichitai, "⚠️ 確認不可", "新着情報セクション見つからず", url=url, pub_date=pub_date)]

    # セクション配下のリンクを収集
    topics = []
    container = shinchaku.parent
    for a in container.find_all("a"):
        title = a.get_text(strip=True)
        href  = a.get("href", "")
        if title and href:
            topics.append({"title": title, "href": href})

    if not topics:
        for sibling in shinchaku.find_next_siblings():
            if sibling.name in ["h2", "h3"] and sibling != shinchaku:
                break
            for a in sibling.find_all("a"):
                title = a.get_text(strip=True)
                href  = a.get("href", "")
                if title:
                    topics.append({"title": title, "href": href})

    if not topics:
        print(f"[{jichitai}] ⚠️ トピック読取不可")
        return [make_row(jichitai, "⚠️ 確認不可", "トピック読取不可", url=url, pub_date=pub_date)]

    ACTIVE_KW = ["募集", "入札公告", "公募", "売払", "公売", "処分", "売却"]
    RESULT_KW = ["結果", "落札", "成約"]

    active_topics = [
        t for t in topics
        if any(kw in t["title"] for kw in ACTIVE_KW)
        and not any(kw in t["title"] for kw in RESULT_KW)
    ]

    if not active_topics:
        print(f"[{jichitai}] ❌ なし（結果系トピックのみ、または該当なし）")
        return [make_row(jichitai, "❌ なし・終了", "結果系トピックのみまたは該当なし", url=url, pub_date=pub_date)]

    rows = []
    for t in active_topics:
        href = t["href"]
        if href and not href.startswith("http"):
            href = "https://www.pref.osaka.lg.jp" + href
        detail_soup, _ = fetch_page(href)
        time.sleep(1)
        location = ""
        period   = ""
        detail_pub = pub_date
        if detail_soup:
            text = detail_soup.get_text(separator="\n")
            m = re.search(r"所在地[：:]\s*(.+?)(?:\n|$)", text)
            if m:
                location = m.group(1).strip()
            m = re.search(r"(?:申込|受付)期間[：:]\s*(.+?)(?:\n|$)", text)
            if m:
                period = m.group(1).strip()
            detail_pub = extract_page_date(detail_soup) or pub_date
        rows.append(make_row(jichitai, "✅ あり", t["title"], location, period, href, detail_pub))

    print(f"[{jichitai}] ✅ あり: {len(rows)}件")
    return rows


# ----------------------------------------
# 2. 大阪府2（府営住宅用地活用事業）
# ----------------------------------------
def parse_osaka_pref2():
    url = "https://www.pref.osaka.lg.jp/sumai/sumai/fueijuutaku/youchishobun/index.html"
    jichitai = "大阪府2（府営住宅用地）"

    soup, err = fetch_page(url)
    if err:
        print(f"[{jichitai}] ⚠️ {err}")
        return [make_row(jichitai, "⚠️ 確認不可", f"アクセスエラー: {err}", url=url)]

    def get_reiwa_year(title):
        m = re.search(r"令和(\d+)年度", title)
        if m:
            return int(m.group(1))
        m = re.search(r"R(\d+)年度", title)
        if m:
            return int(m.group(1))
        return 0

    year_links = []
    for a in soup.find_all("a"):
        title = a.get_text(strip=True)
        if re.search(r"令和\d+年度|R\d+年度", title):
            href = a.get("href", "")
            year_links.append({"title": title, "href": href, "year": get_reiwa_year(title)})

    if not year_links:
        print(f"[{jichitai}] ⚠️ 年度リンク見つからず")
        return [make_row(jichitai, "⚠️ 確認不可", "年度リンク見つからず", url=url)]

    max_year = max(x["year"] for x in year_links)
    latest_links = [x for x in year_links if x["year"] == max_year]
    print(f"[{jichitai}] 最新年度: 令和{max_year}年度, リンク数: {len(latest_links)}")

    rows = []

    for lv2 in latest_links:
        href2 = lv2["href"]
        if href2 and not href2.startswith("http"):
            href2 = "https://www.pref.osaka.lg.jp" + href2

        soup2, err2 = fetch_page(href2)
        time.sleep(1)
        if err2:
            rows.append(make_row(jichitai, "⚠️ 確認不可", f"第2階層アクセス不可: {lv2['title']}", url=href2))
            continue

        lv3_links = []
        for a in soup2.find_all("a"):
            t = a.get_text(strip=True)
            h = a.get("href", "")
            if t and h and any(kw in t for kw in ["売却", "予定", "物件", "募集"]):
                lv3_links.append({"title": t, "href": h})

        if not lv3_links:
            lv3_links = [{"title": lv2["title"], "href": href2}]
            soups = [soup2]
        else:
            soups = [None] * len(lv3_links)

        for i, lv3 in enumerate(lv3_links):
            href3 = lv3["href"]
            if href3 and not href3.startswith("http"):
                href3 = "https://www.pref.osaka.lg.jp" + href3

            if soups[i] is None:
                soup3, err3 = fetch_page(href3)
                time.sleep(1)
                if err3:
                    rows.append(make_row(jichitai, "⚠️ 確認不可", f"第3階層アクセス不可: {lv3['title']}", url=href3))
                    continue
            else:
                soup3 = soups[i]

            pub_date = extract_page_date(soup3)

            locations = []
            for h_tag in soup3.find_all(["h2", "h3", "h4", "h5", "th", "dt", "strong", "b"]):
                if any(kw in h_tag.get_text() for kw in ["売却予定物件", "売却物件"]):
                    for sib in h_tag.find_next_siblings():
                        sib_text = sib.get_text(separator="\n", strip=True)
                        locs = re.findall(r"所在地[：:]\s*(.+?)(?:\n|$)", sib_text)
                        locations.extend([l.strip() for l in locs if l.strip()])
                        if sib.name in ["h2", "h3", "h4"]:
                            break

            if not locations:
                for table in soup3.find_all("table"):
                    if "所在地" in table.get_text() or "売却" in table.get_text():
                        for tr in table.find_all("tr"):
                            cells = tr.find_all(["td", "th"])
                            for ci, cell in enumerate(cells):
                                if "所在地" in cell.get_text() and ci + 1 < len(cells):
                                    loc_text = cells[ci + 1].get_text(strip=True)
                                    if loc_text:
                                        locations.append(loc_text)

            if locations:
                target_locs = [l for l in locations if is_target_area(l)]
                if target_locs:
                    for loc in target_locs:
                        rows.append(make_row(jichitai, "✅ あり", lv3["title"], loc, url=href3, pub_date=pub_date))
                    print(f"[{jichitai}] ✅ 対象エリア該当: {target_locs}")
                else:
                    print(f"[{jichitai}] ❌ 対象エリア外: {locations[:2]}")
            else:
                print(f"[{jichitai}] ⚠️ 所在地読取不可: {lv3['title']}")
                rows.append(make_row(jichitai, "⚠️ 確認不可", f"所在地読取不可: {lv3['title']}", url=href3, pub_date=pub_date))

    if not rows:
        print(f"[{jichitai}] ❌ 対象エリア該当物件なし")
        rows.append(make_row(jichitai, "❌ なし・終了", "対象エリア該当物件なし", url=url))

    return rows


# ----------------------------------------
# 3 & 4. 大阪市①②（契約管財局・水道局）
# ----------------------------------------
def parse_osaka_city():
    url = "https://www.city.osaka.lg.jp/keiyakukanzai/page/0000577262.html"

    soup, err = fetch_page(url)
    if err:
        print(f"[大阪市①②] ⚠️ {err}")
        return [
            make_row("大阪市①（契約管財局）", "⚠️ 確認不可", f"アクセスエラー: {err}", url=url),
            make_row("大阪市②（水道局）",    "⚠️ 確認不可", f"アクセスエラー: {err}", url=url),
        ]

    rows = []
    for section_name, jichitai in [
        ("契約管財局実施分", "大阪市①（契約管財局）"),
        ("水道局実施分",     "大阪市②（水道局）"),
    ]:
        rows.extend(_parse_osaka_city_section(soup, url, section_name, jichitai))
    return rows


def _parse_osaka_city_section(soup, url, section_name, jichitai):
    section_heading = None
    for tag in soup.find_all(["h2", "h3", "h4", "h5", "p", "div", "strong", "span"]):
        if section_name in tag.get_text():
            section_heading = tag
            break

    if section_heading is None:
        print(f"[{jichitai}] ⚠️ セクション '{section_name}' が見つかりません")
        return [make_row(jichitai, "⚠️ 確認不可", "セクション見つからず", url=url)]

    section_nodes = []
    other_sections = {"契約管財局実施分", "水道局実施分"} - {section_name}
    for sib in section_heading.find_next_siblings():
        if any(kw in sib.get_text() for kw in other_sections):
            break
        section_nodes.append(sib)

    table    = None
    pub_date = ""
    for node in section_nodes:
        node_text = node.get_text()
        if not pub_date:
            d_m = re.search(r"令和\d+年\d+月\d+日|\d{4}年\d+月\d+日", node_text)
            if d_m:
                pub_date = d_m.group()
        candidate = node if node.name == "table" else node.find("table")
        if candidate and ("所在地" in candidate.get_text() or "物件" in candidate.get_text()):
            table = candidate
            break

    if table is None:
        section_text = " ".join(n.get_text() for n in section_nodes)
        if any(kw in section_text for kw in ["ありません", "ございません", "予定はありません"]):
            print(f"[{jichitai}] ❌ なし（ページ記載より）")
            return [make_row(jichitai, "❌ なし・終了", "現在案件なし（ページ記載）", url=url, pub_date=pub_date)]
        print(f"[{jichitai}] ⚠️ 土地テーブルが見つかりません")
        return [make_row(jichitai, "⚠️ 確認不可", "土地テーブル読取不可", url=url, pub_date=pub_date)]

    all_rows_data = []
    headers = []
    for i, tr in enumerate(table.find_all("tr")):
        cells = [td.get_text(strip=True) for td in tr.find_all(["th", "td"])]
        if i == 0:
            headers = cells
        else:
            if any(c.strip() for c in cells):
                all_rows_data.append(cells)

    if not all_rows_data:
        print(f"[{jichitai}] ❌ テーブルにデータ行なし")
        return [make_row(jichitai, "❌ なし・終了", "テーブルにデータなし", url=url, pub_date=pub_date)]

    loc_idx = next((i for i, h in enumerate(headers) if "所在地" in h or "住居表示" in h), 1)
    num_idx = next((i for i, h in enumerate(headers) if "物件番号" in h or "番号" in h), 0)

    result_rows = []
    all_locs = []
    for row in all_rows_data:
        loc = row[loc_idx] if loc_idx < len(row) else ""
        num = row[num_idx] if num_idx < len(row) else ""
        all_locs.append(loc)
        if is_target_area(loc):
            result_rows.append(make_row(jichitai, "✅ あり", f"物件番号: {num}", loc, url=url, pub_date=pub_date))

    if result_rows:
        print(f"[{jichitai}] ✅ あり: 対象エリア {len(result_rows)}件")
        return result_rows
    elif all_locs:
        print(f"[{jichitai}] ❌ 対象エリア外 ({len(all_locs)}件確認)")
        return [make_row(jichitai, "❌ なし・終了", f"物件あり・対象エリア外 ({len(all_locs)}件)", url=url, pub_date=pub_date)]
    else:
        return [make_row(jichitai, "❌ なし・終了", "物件情報なし", url=url, pub_date=pub_date)]


# ----------------------------------------
# 5. 近畿財務局
# ----------------------------------------
def parse_kinki_zaimu():
    url = "https://lfb.mof.go.jp/kinki/during/index2_00001.html"
    jichitai = "近畿財務局"

    soup, err = fetch_page(url)
    if err:
        print(f"[{jichitai}] ⚠️ {err}")
        return [make_row(jichitai, "⚠️ 確認不可", f"アクセスエラー: {err}", url=url)]

    pub_date = extract_page_date(soup)

    table = None
    for t in soup.find_all("table"):
        if "物件" in t.get_text() or "所在地" in t.get_text() or "番号" in t.get_text():
            table = t
            break

    if table is None:
        page_text = soup.get_text()
        if "公開中の情報はありません" in page_text or "現在、公開中" in page_text:
            print(f"[{jichitai}] ❌ なし（公開中情報なし）")
            return [make_row(jichitai, "❌ なし・終了", "公開中の情報はありません（ページ記載）", url=url, pub_date=pub_date)]
        print(f"[{jichitai}] ⚠️ 物件一覧テーブルが見つかりません")
        return [make_row(jichitai, "⚠️ 確認不可", "物件一覧テーブル読取不可", url=url, pub_date=pub_date)]

    headers   = []
    rows_data = []
    for i, tr in enumerate(table.find_all("tr")):
        cells = [td.get_text(strip=True) for td in tr.find_all(["th", "td"])]
        if i == 0:
            headers = cells
        else:
            if any(c.strip() for c in cells):
                rows_data.append(cells)

    if not rows_data:
        print(f"[{jichitai}] ❌ テーブルにデータなし")
        return [make_row(jichitai, "❌ なし・終了", "テーブルにデータなし", url=url, pub_date=pub_date)]

    num_idx  = next((i for i, h in enumerate(headers) if "物件番号" in h or "番号" in h), 0)
    name_idx = next((i for i, h in enumerate(headers) if "物件名" in h or "名称" in h), min(1, len(headers)-1))
    loc_idx  = next((i for i, h in enumerate(headers) if "所在地" in h or "住所" in h), min(2, len(headers)-1))

    result_rows = []
    all_items   = []
    for row in rows_data:
        num  = row[num_idx]  if num_idx  < len(row) else ""
        name = row[name_idx] if name_idx < len(row) else ""
        loc  = row[loc_idx]  if loc_idx  < len(row) else ""
        if any(kw in name for kw in ["問い合わせ", "電話", "TEL", "担当"]):
            continue
        all_items.append(f"{name}: {loc}")
        if is_target_area(loc) or is_target_area(name):
            summary = f"物件番号: {num} {name}".strip()
            result_rows.append(make_row(jichitai, "✅ あり", summary, loc, url=url, pub_date=pub_date))

    if result_rows:
        print(f"[{jichitai}] ✅ あり: 対象エリア {len(result_rows)}件")
        return result_rows
    elif all_items:
        print(f"[{jichitai}] ❌ 対象エリア外 ({len(all_items)}件確認)")
        return [make_row(jichitai, "❌ なし・終了", f"物件あり・対象エリア外 ({len(all_items)}件)", url=url, pub_date=pub_date)]
    else:
        return [make_row(jichitai, "❌ なし・終了", "物件情報なし", url=url, pub_date=pub_date)]


# ----------------------------------------
# 6. 松原市
# ----------------------------------------
def parse_matsubara():
    url = "https://www.city.matsubara.lg.jp/docs"
    jichitai = "松原市"
    keywords = ["入札", "市有地", "売払い", "売払", "売却"]

    soup, err = fetch_page(url)
    if err:
        print(f"[{jichitai}] ⚠️ {err}")
        return [make_row(jichitai, "⚠️ 確認不可", f"アクセスエラー: {err}", url=url)]

    pub_date = extract_page_date(soup)

    articles = []
    for a in soup.find_all("a"):
        title = a.get_text(strip=True)
        href  = a.get("href", "")
        if any(kw in title for kw in keywords):
            # リンク隣接テキストから日付を探す
            parent_text = a.parent.get_text() if a.parent else ""
            art_date = ""
            d_m = re.search(r"令和\d+年\d+月\d+日|\d{4}年\d+月\d+日|\d{4}/\d+/\d+", parent_text)
            if d_m:
                art_date = d_m.group()
            if href and not href.startswith("http"):
                href = "https://www.city.matsubara.lg.jp" + href
            articles.append({"title": title, "href": href, "date": art_date or pub_date})

    if articles:
        rows = [make_row(jichitai, "✅ あり", a["title"], url=a["href"], pub_date=a["date"]) for a in articles]
        print(f"[{jichitai}] ✅ あり: {len(articles)}件")
        return rows
    else:
        print(f"[{jichitai}] ❌ なし（該当記事なし）")
        return [make_row(jichitai, "❌ なし・終了", "該当記事なし", url=url, pub_date=pub_date)]


# ----------------------------------------
# 7. 堺市
# ----------------------------------------
def parse_sakai():
    url = "https://www.city.sakai.lg.jp/sangyo/nyusatsu/koubo/shiyuchibaikyaku/bosyu/index.html"
    jichitai = "堺市"

    soup, err = fetch_page(url)
    if err:
        print(f"[{jichitai}] ⚠️ {err}")
        return [make_row(jichitai, "⚠️ 確認不可", f"アクセスエラー: {err}", url=url)]

    pub_date = extract_page_date(soup)

    boshu_heading = None
    for tag in soup.find_all(["h2", "h3", "h4", "h5", "p", "div", "strong"]):
        if "現在募集している案件" in tag.get_text():
            boshu_heading = tag
            break

    if boshu_heading is None:
        print(f"[{jichitai}] ⚠️ 『現在募集している案件』セクションが見つかりません")
        return [make_row(jichitai, "⚠️ 確認不可", "セクション見つからず", url=url, pub_date=pub_date)]

    cases = []
    for sib in boshu_heading.find_next_siblings():
        if sib.name in ["h2", "h3", "h4"] and "現在募集" not in sib.get_text():
            break
        tbl = sib if sib.name == "table" else sib.find("table")
        if tbl:
            for tr in tbl.find_all("tr")[1:]:
                cells = [td.get_text(strip=True) for td in tr.find_all(["td", "th"])]
                if any(c.strip() for c in cells):
                    cases.append(" | ".join(cells))
            if cases:
                break
        lst = sib if sib.name in ["ul", "ol"] else sib.find(["ul", "ol"])
        if lst:
            for li in lst.find_all("li"):
                t = li.get_text(strip=True)
                if t:
                    cases.append(t)
            if cases:
                break

    if cases:
        print(f"[{jichitai}] ✅ あり: {len(cases)}件")
        return [make_row(jichitai, "✅ あり", case, url=url, pub_date=pub_date) for case in cases]
    else:
        print(f"[{jichitai}] ❌ なし（募集案件なし）")
        return [make_row(jichitai, "❌ なし・終了", "現在募集案件なし", url=url, pub_date=pub_date)]


# ----------------------------------------
# 8. 藤井寺市
# ----------------------------------------
def parse_fujiidera():
    url = "https://www.city.fujiidera.lg.jp/soshiki/somubu/soumu/youchikanzai/1471333416329.html"
    jichitai = "藤井寺市"

    soup, err = fetch_page(url)
    if err:
        print(f"[{jichitai}] ⚠️ {err}")
        return [make_row(jichitai, "⚠️ 確認不可", f"アクセスエラー: {err}", url=url)]

    # ページ更新日を取得
    page_text = soup.get_text(separator="\n")
    pub_date = ""
    d_m = re.search(r"更新日[：:]\s*(令和\d+年\d+月\d+日|\d{4}年\d+月\d+日)", page_text)
    if d_m:
        pub_date = d_m.group(1)
    else:
        pub_date = extract_page_date(soup)

    # 「売却物件」見出し配下のテーブルを探す
    table = None
    for tag in soup.find_all(["h2", "h3", "h4", "h5", "p", "strong", "b"]):
        if "売却物件" in tag.get_text():
            for sib in tag.find_next_siblings():
                t = sib if sib.name == "table" else sib.find("table")
                if t:
                    table = t
                    break
                if sib.name in ["h2", "h3"]:
                    break
            break

    if table is None:
        for t in soup.find_all("table"):
            if any(kw in t.get_text() for kw in ["所在地", "地番", "売却"]):
                table = t
                break

    if table is None:
        if any(kw in page_text for kw in ["売却物件はありません", "現在、売却物件はありません"]):
            print(f"[{jichitai}] ❌ なし（ページ記載）")
            return [make_row(jichitai, "❌ なし・終了", "売却物件はありません（ページ記載）", url=url, pub_date=pub_date)]
        print(f"[{jichitai}] ⚠️ 売却物件テーブル読取不可")
        return [make_row(jichitai, "⚠️ 確認不可", "売却物件テーブル読取不可", url=url, pub_date=pub_date)]

    headers   = []
    rows_data = []
    for i, tr in enumerate(table.find_all("tr")):
        cells = [td.get_text(strip=True) for td in tr.find_all(["th", "td"])]
        if i == 0 and any(kw in " ".join(cells) for kw in ["所在地", "地番", "物件"]):
            headers = cells
        else:
            if any(c.strip() for c in cells):
                rows_data.append(cells)

    if not rows_data:
        print(f"[{jichitai}] ❌ テーブルにデータなし")
        return [make_row(jichitai, "❌ なし・終了", "売却物件テーブルにデータなし", url=url, pub_date=pub_date)]

    loc_idx = next((i for i, h in enumerate(headers) if "所在地" in h or "地番" in h), 0)
    locations = [row[loc_idx] for row in rows_data if loc_idx < len(row) and row[loc_idx].strip()]
    location_str = "・".join(locations[:3])

    # 申込期間を探す
    period = ""
    for pattern in [
        r"申込[み受付期間]*[：:]\s*(.+?)(?:\n|$)",
        r"受付期間[：:]\s*(.+?)(?:\n|$)",
        r"申込受付期間[：:]\s*(.+?)(?:\n|$)",
    ]:
        m = re.search(pattern, page_text)
        if m:
            period = m.group(1).strip()
            break

    if period:
        end_date = extract_period_end(period)
        if end_date:
            if end_date >= TODAY:
                status = "✅ あり"
                print(f"[{jichitai}] ✅ あり（受付中: {period}）")
            else:
                status = "❌ なし・終了"
                print(f"[{jichitai}] ❌ 受付終了（{period}）")
        else:
            status = "⚠️ 確認不可"
            print(f"[{jichitai}] ⚠️ 申込期間の終了日を特定できません: {period}")
    else:
        status = "⚠️ 確認不可"
        print(f"[{jichitai}] ⚠️ 申込期間が読み取れません")

    return [make_row(jichitai, status, "売却物件あり", location_str, period, url, pub_date)]


# ----------------------------------------
# 9. 羽曳野市
# ----------------------------------------
def parse_habikino():
    url = "https://www.city.habikino.lg.jp/soshiki/soumu/soumu_zaikanyouchi/soumu_zaikanyouchi_oshirase/index.html"
    jichitai = "羽曳野市"
    keywords = ["入札", "市有地", "売払い", "売払", "売却"]

    soup, err = fetch_page(url)
    if err:
        print(f"[{jichitai}] ⚠️ {err}")
        return [make_row(jichitai, "⚠️ 確認不可", f"アクセスエラー: {err}", url=url)]

    pub_date = extract_page_date(soup)

    articles = []
    for a in soup.find_all("a"):
        title = a.get_text(strip=True)
        href  = a.get("href", "")
        if any(kw in title for kw in keywords):
            parent_text = a.parent.get_text() if a.parent else ""
            art_date = ""
            d_m = re.search(r"令和\d+年\d+月\d+日|\d{4}年\d+月\d+日|\d{4}/\d+/\d+", parent_text)
            if d_m:
                art_date = d_m.group()
            if href and not href.startswith("http"):
                href = "https://www.city.habikino.lg.jp" + href
            articles.append({"title": title, "href": href, "date": art_date or pub_date})

    if not articles:
        for li in soup.find_all("li"):
            text = li.get_text(strip=True)
            if any(kw in text for kw in keywords):
                articles.append({"title": text, "href": "", "date": pub_date})

    if articles:
        rows = [make_row(jichitai, "✅ あり", a["title"], url=a["href"] or url, pub_date=a["date"]) for a in articles]
        print(f"[{jichitai}] ✅ あり: {len(articles)}件")
        return rows
    else:
        print(f"[{jichitai}] ❌ なし（該当キーワード記事なし）")
        return [make_row(jichitai, "❌ なし・終了", "該当キーワード記事なし", url=url, pub_date=pub_date)]


# ----------------------------------------
# 10. 八尾市
# ----------------------------------------
def parse_yao():
    url = "https://www.city.yao.osaka.jp/sangyou_business/nyuusatsu_keiyaku/1014663/1011828/1017071/index.html"
    jichitai = "八尾市"
    KW_INCLUDE = ["市有地", "土地", "売払", "売却", "一般競争入札"]
    KW_EXCLUDE = ["バス", "車両", "メンテナンス", "業務委託", "清掃", "修繕", "道路", "建物", "備品", "リース"]

    soup, err = fetch_page(url)
    if err:
        print(f"[{jichitai}] ⚠️ {err}")
        return [make_row(jichitai, "⚠️ 確認不可", f"アクセスエラー: {err}", url=url)]

    pub_date = extract_page_date(soup)

    all_links = []
    for a in soup.find_all("a"):
        title = a.get_text(strip=True)
        href  = a.get("href", "")
        if title and len(title) > 2:
            all_links.append({"title": title, "href": href})

    target_links = [
        lnk for lnk in all_links
        if any(kw in lnk["title"] for kw in KW_INCLUDE)
        and not any(kw in lnk["title"] for kw in KW_EXCLUDE)
    ]

    print(f"[{jichitai}] リンク総数: {len(all_links)}, 対象候補: {len(target_links)}")

    if not target_links:
        print(f"[{jichitai}] ❌ なし（該当リンクなし）")
        return [make_row(jichitai, "❌ なし・終了", "該当キーワードリンクなし", url=url, pub_date=pub_date)]

    rows = []
    for link in target_links:
        href = link["href"]
        if href and not href.startswith("http"):
            href = "https://www.city.yao.osaka.jp" + href

        detail_soup, detail_err = fetch_page(href)
        time.sleep(1)

        if detail_err:
            rows.append(make_row(jichitai, "⚠️ 確認不可", link["title"], url=href, pub_date=pub_date))
            continue

        detail_pub = extract_page_date(detail_soup) or pub_date
        page_text  = detail_soup.get_text(separator="\n")
        period = ""
        for pattern in [
            r"申込期間[：:]\s*(.+?)(?:\n|$)",
            r"申し込み期間[：:]\s*(.+?)(?:\n|$)",
            r"受付期間[：:]\s*(.+?)(?:\n|$)",
            r"申込受付期間[：:]\s*(.+?)(?:\n|$)",
        ]:
            m = re.search(pattern, page_text)
            if m:
                period = m.group(1).strip()
                break

        if period:
            end_date = extract_period_end(period)
            if end_date:
                if end_date >= TODAY:
                    rows.append(make_row(jichitai, "✅ あり", link["title"], period=period, url=href, pub_date=detail_pub))
                    print(f"[{jichitai}] ✅ あり（受付中: {period}）: {link['title']}")
                else:
                    rows.append(make_row(jichitai, "❌ なし・終了", link["title"], period=period, url=href, pub_date=detail_pub))
                    print(f"[{jichitai}] ❌ 申込期間終了（{period}）")
            else:
                rows.append(make_row(jichitai, "⚠️ 確認不可", link["title"], period=f"終了日特定不可: {period}", url=href, pub_date=detail_pub))
        else:
            rows.append(make_row(jichitai, "⚠️ 確認不可", link["title"], period="申込期間読取不可", url=href, pub_date=detail_pub))

    return rows


print("✅ パーサー関数定義完了（全10サイト）")

# ============================================================
# セル4: メイン実行
# ============================================================
from collections import defaultdict

print("=" * 60)
print("公有地売却・入札情報 パトロール開始")
print(f"調査日: {TODAY_STR}")
print("=" * 60)

all_rows = []

parsers = [
    ("大阪府1（財産活用課）",          parse_osaka_pref1),
    ("大阪府2（府営住宅用地）",         parse_osaka_pref2),
    ("大阪市①②（契約管財局・水道局）", parse_osaka_city),
    ("近畿財務局",                      parse_kinki_zaimu),
    ("松原市",                          parse_matsubara),
    ("堺市",                            parse_sakai),
    ("藤井寺市",                        parse_fujiidera),
    ("羽曳野市",                        parse_habikino),
    ("八尾市",                          parse_yao),
]

for name, parser_func in parsers:
    print(f"\n--- {name} ---")
    try:
        rows = parser_func()
        all_rows.extend(rows)
    except Exception as e:
        import traceback
        print(f"[{name}] ❌ 予期しないエラー: {e}")
        traceback.print_exc()
        all_rows.append(make_row(name, "⚠️ 確認不可", f"予期しないエラー: {e}"))
    time.sleep(2)

print("\n" + "=" * 60)
print(f"スクレイピング完了: {len(all_rows)}行")
print("=" * 60)

# ==============================================================
# ① パトロール結果シート（全件詳細）
# ==============================================================
DETAIL_HEADER = ["調査日", "自治体", "ステータス", "案件概要", "所在地", "申込期間", "URL", "公開日・更新日"]

ws.clear()
time.sleep(1)
ws.update("A1", [DETAIL_HEADER] + all_rows)
ws.format("A1:H1", {
    "textFormat": {"bold": True},
    "backgroundColor": {"red": 0.851, "green": 0.918, "blue": 0.984},
})
print(f"\n✅ パトロール結果シート書き込み完了: {len(all_rows)}行")

# ==============================================================
# ② サマリーシート（10サイト × 1行）
# ==============================================================

# 自治体ごとに行をグループ化
site_rows = defaultdict(list)
for row in all_rows:
    site_rows[row[1]].append(row)

def status_priority(status):
    """ステータスの優先度（低い = 重要）。✅ > ⚠️ > ❌"""
    if "✅" in status: return 0
    if "⚠️" in status: return 1
    return 2

summary_rows = []
for site in SITES_ORDER:
    matching = site_rows.get(site, [])

    if not matching:
        # パーサーが結果を返さなかった（実行されていない）
        summary_rows.append([site, "⚠️ 確認不可", "", "（実行されませんでした）", "", ""])
        continue

    # 最高優先度のステータスを採用
    best_row    = min(matching, key=lambda r: status_priority(r[2]))
    best_status = best_row[2]

    # ✅ 行（エリア内案件あり）を優先してサマリーを作成
    active = [r for r in matching if "✅" in r[2]]
    if active:
        summary   = " / ".join(filter(None, [r[3] for r in active]))[:100]
        location  = " / ".join(filter(None, [r[4] for r in active]))[:100]
        period    = " / ".join(dict.fromkeys(filter(None, [r[5] for r in active])))  # 重複除去
        url       = active[0][6]
        pub_date  = next((r[7] for r in active if r[7]), "")
    else:
        summary   = best_row[3]
        location  = best_row[4]
        period    = best_row[5]
        url       = best_row[6]
        pub_date  = best_row[7]

    summary_rows.append([site, best_status, pub_date, summary, location, period, url])

# サマリーシートへ書き込み
SUMMARY_HEADER = ["自治体", "ステータス", "公開日・更新日", "案件概要（エリア内物件名）", "所在地", "申込期間", "URL"]
TITLE_ROW      = [f"公有地売却・入札情報パトロール　調査日：{TODAY_STR}", "", "", "", "", "", ""]

ws_summary.clear()
time.sleep(1)
ws_summary.update("A1", [TITLE_ROW, SUMMARY_HEADER] + summary_rows)

# タイトル行（A1）の書式
ws_summary.format("A1", {
    "textFormat": {"bold": True, "fontSize": 12},
    "backgroundColor": {"red": 0.267, "green": 0.447, "blue": 0.769},  # 濃い青
})
# A1 文字色を白に
ws_summary.format("A1", {"textFormat": {"bold": True, "fontSize": 12, "foregroundColor": {"red": 1, "green": 1, "blue": 1}}})

# ヘッダー行（A2:G2）
ws_summary.format("A2:G2", {
    "textFormat": {"bold": True},
    "backgroundColor": {"red": 0.851, "green": 0.918, "blue": 0.984},
})

# ステータス列（B列）の条件付き書式を行単位で色付け
for i, srow in enumerate(summary_rows):
    row_num = i + 3  # データは3行目から
    status  = srow[1]
    if "✅" in status:
        bg = {"red": 0.851, "green": 0.969, "blue": 0.827}  # 薄緑
    elif "⚠️" in status:
        bg = {"red": 1.0,   "green": 0.949, "blue": 0.800}  # 薄黄
    else:
        bg = {"red": 0.957, "green": 0.957, "blue": 0.957}  # 薄灰
    ws_summary.format(f"A{row_num}:G{row_num}", {"backgroundColor": bg})

spreadsheet_url = f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}"
print(f"✅ サマリーシート書き込み完了: {len(summary_rows)}行")
print(f"\n📊 スプレッドシート: {spreadsheet_url}")

# ==============================================================
# コンソールサマリー
# ==============================================================
print("\n" + "=" * 60)
print(f"【調査結果サマリー】  {TODAY_STR}")
print("=" * 60)
for srow in summary_rows:
    site, status, pub, summary, loc, period, url = srow
    print(f"{status}  {site}")
    if summary:
        print(f"      案件概要: {summary[:60]}")
    if loc:
        print(f"      所在地:   {loc[:60]}")
    if period:
        print(f"      申込期間: {period[:60]}")
